### ISSUE TITLE
Default path for `styleLintConfigFile` incorrect.

### ISSUE THREAD

**Issue by nathanshower** [kanopi/kanopi-pack#45]
The default path for the `styleLintConfigFile` is documented as `node_modules/@kanopi/pack/configuration/tools/stylelint.config.js`. When attempting to take the default the path it is actually looking for is `node_modules/@kanopi/pack/src/configuration/tools/stylelint.config.js`.

Attempting to use the default path results in the following error:

```
ERROR in [stylelint] ENOENT: no such file or directory, open '/var/www/web/wp-content/themes/custom/node_modules/@kanopi/pack/src/configuration/tools/stylelint.config.js'
```

This issue may affect the `styleLintIgnorePath` and/or the `styleLintConfigBaseDir` as well.

**Comment by rleeson** [comment]
Closed in #46
